// Auto-generated mobile test assets index (Phase 7)
// Generated by MobileTestGenerationAgent

module.exports = {
  // Android
  AndroidSearchFlow: require("./flows/android/search.flow"),
  AndroidCartFlow: require("./flows/android/cart.flow"),
  AndroidNativeHomePage: require("./page-objects/native/android-native-home-page"),
  AndroidHybridHomePage: require("./page-objects/hybrid/android-hybrid-home-page"),

  // iOS
  IOSSearchFlow: require("./flows/ios/search.flow"),
  IOSCartFlow: require("./flows/ios/cart.flow"),
  IOSNativeHomePage: require("./page-objects/native/ios-native-home-page"),
  IOSHybridHomePage: require("./page-objects/hybrid/ios-hybrid-home-page"),

  // Locators
  androidNativeLocators: require("./locators/android/native-home.locators"),
  androidHybridLocators: require("./locators/android/hybrid-home.locators"),
  iosNativeLocators: require("./locators/ios/native-home.locators"),
  iosHybridLocators: require("./locators/ios/hybrid-home.locators")
};
