const fs = require('fs-extra');
const path = require('path');

class OutputWriter {
  constructor(opts={}){
    this.dryRun = opts.dryRun !== undefined ? opts.dryRun : true;
    this.generatedDir = path.join(process.cwd(), 'generated-features');
    this.metaDir = path.join(process.cwd(), 'ai', 'output');
    fs.ensureDirSync(this.generatedDir);
    fs.ensureDirSync(this.metaDir);
  }

  featureFileName(feature) {
    const safe = (feature.title||'generated').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80) || `gen-${Date.now()}`;
    return `${safe}.feature`;
  }

  isDuplicateFeature(title) {
    const fname = this.featureFileName({title});
    const p = path.join(this.generatedDir, fname);
    if (!fs.existsSync(p)) return false;
    const existing = fs.readFileSync(p,'utf8');
    return existing.includes(title);
  }

  writeFeature(featureObj) {
    const fname = this.featureFileName(featureObj);
    const outPath = path.join(this.generatedDir, fname);
    const metaPath = path.join(this.metaDir, `${featureObj.id}.json`);

    // prepare gherkin
    const parts = [];
    parts.push(`# AUTOGENERATED - review before use`);
    parts.push(`# id: ${featureObj.id}`);
    parts.push(`Feature: ${featureObj.title}`);
    for (const sc of featureObj.scenarios) {
      parts.push(`\n  @generated @confidence(${sc.confidence})`);
      parts.push(`  Scenario: ${sc.title}`);
      for (const step of sc.steps) parts.push(`    ${step.text}`);
    }
    const content = parts.join('\n');

    if (this.dryRun) {
      // write metadata only
      fs.writeJsonSync(metaPath, { feature: featureObj, generatedAt: new Date().toISOString() }, { spaces: 2 });
      return { metaPath, wouldWrite: outPath };
    }

    fs.writeFileSync(outPath, content, 'utf8');
    fs.writeJsonSync(metaPath, { feature: featureObj, generatedAt: new Date().toISOString() }, { spaces: 2 });
    return { outPath, metaPath };
  }

  // static helpers
  static isDuplicateFeatureStatic(title) {
    const writer = new OutputWriter({ dryRun: true });
    return writer.isDuplicateFeature(title);
  }
}

module.exports = OutputWriter;
