/**
 * plugins/agents/samplePluginAgent.js
 *
 * Sample plugin agent demonstrating the plugin architecture.
 * Users can add agents here WITHOUT modifying any core framework files.
 *
 * This agent is auto-discovered by AgentRegistry from the plugins/agents/ directory.
 * It registers a custom event and runs on every execution.
 */

const fs = require('fs-extra');
const path = require('path');

const bus = require('../../ai/core/EventBus');

// Register a custom event type
bus.registerCustomEvent('PluginExecutionCompleted', 'Fired when a plugin agent completes execution');

class SamplePluginAgent {
  async run(input = {}) {
    console.log('[SamplePluginAgent] Plugin agent executed successfully');
    console.log('[SamplePluginAgent] Platform:', input.platform || 'unknown');

    // Write a report to show it works
    const reportDir = path.join(process.cwd(), 'reports', 'ai', 'plugins');
    fs.ensureDirSync(reportDir);
    const reportPath = path.join(reportDir, 'sample-plugin-report.md');
    fs.writeFileSync(reportPath, [
      '# Sample Plugin Report',
      '',
      '**Generated:** ' + new Date().toISOString(),
      '**Platform:** ' + (input.platform || 'unknown'),
      '',
      'This report was generated by a plugin agent.',
      'No core framework files were modified to add this agent.',
      '',
      '## How Plugin Architecture Works',
      '',
      '1. Place agent files in `plugins/agents/`',
      '2. AgentRegistry auto-discovers them on startup',
      '3. Custom events can be registered via bus.registerCustomEvent()',
      '4. No modification of ai/core/, ai/agents/, or ai/index.js required',
      ''
    ].join('\n'), 'utf8');

    // Fire custom event
    bus.emit('PluginExecutionCompleted', {
      agent: 'samplePluginAgent',
      reportPath: path.relative(process.cwd(), reportPath)
    });

    return {
      ok: true,
      message: 'Plugin agent executed successfully',
      reportPath: path.relative(process.cwd(), reportPath)
    };
  }
}

module.exports = SamplePluginAgent;

// Plugin metadata for AgentRegistry auto-discovery
module.exports.metadata = {
  name: 'Sample Plugin Agent',
  version: '1.0.0',
  description: 'Example plugin agent demonstrating the plugin architecture',
  dependencies: [],
  platforms: ['WEB', 'ANDROID', 'IOS', 'API'],
  tags: ['plugin', 'example'],
  executionStage: 'reporting',
  priority: 5,
  conditions: [{ type: 'always' }],
  retryPolicy: { maxRetries: 0, backoff: 'none' },
  strategy: 'independent',
  responsibilities: ['plugin-demo'],
  lifecycle: 'active'
};
